logging:
  level:
    ROOT: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apistartideia
    username: apistartideia
    password: apistartideia
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: com.example.startaideia.configuration.CustomPhysicalNamingStrategyImpl
    database: POSTGRESQL
    show-sql: true
  liquibase:
    contexts: dev, faker

server:
  port: 3000
  servlet:
    contextPath: /api
